### ISSUE TITLE
Change the exit list used by Tor2web to determine if a user is coming from Behind Tor

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#125]
The exit list currently used by Tor2web to identify if a user visiting a Tor2web site is using Tor or not, is based on Onionoo.

Onionoo do provide the "Relay list" but not exactly the "Exit list"

Following the ticket at  https://trac.torproject.org/projects/tor/ticket/9529 it has been noticed that we should switch to using https://check.torproject.org/exit-addresses to fetch all the tor exit address.

**Comment by fpietrosanti** [comment]
This problem has been spotted on AfriLeaks's tor2web use. /cc @evilaliv3 @virgil

**Comment by virgil** [comment]
small feature, but I support this.  If the format is different can always ping Karsten to add exit-addresses to Onionoo

**Comment by evilaliv3** [comment]
k in   the next days i will evaluate this change and i will push it out in the next release.

**Comment by evilaliv3** [comment]
ok its time to do this! consider this a XMAS gift! thank you god for borning again!

\cc @marceloomens

**Comment by marceloomens** [comment]
I agree with @virgil. It's a small feature that's more of a convenience. We're currently seeing this a lot on Publeaks, with questions by receivers why they can't log in (login denied when not successfully redirected to hidden service address...)

**Comment by evilaliv3** [comment]
bam!

**Comment by marceloomens** [comment]
![I like](http://digitalpublishing101.com/wp-content/uploads/2012/06/Facebook-Like.jpeg)
