### ISSUE TITLE
want to specify a list of multiple base_hosts

### ISSUE THREAD

**Issue by virgil** [globaleaks/Tor2web#201]
Would help diagnose problems to give each backend instance a unique basehost that only it responds to.

**Comment by evilaliv3** [comment]
can you explain better with some examples?

**Comment by virgil** [comment]
I want to give each server a unique identifier as well as the global
identifier.  e.g.,

basehosts= [onion.city, www2.onion.city]


and then another machine would have:
basehosts= [onion.city, www3.onion.city]


this would allow me to specify that a request go through a particular
machine by specifying wwwX.onion.city

**Comment by evilaliv3** [comment]
ok but can you clarify me the use case?
i see various issues here:
1) onion.city, www2.onion.city mixing two similar regexp that will match together can cause problems
2) adding multiple patterns make the system slower.

if you can clarify with a real world scenario that would benefit of this? this way i can try to think to a solution for this.

i dont get an example in wich you prefer you have the need that a server is configured for two basehosts for example as a dns can do this kind of round robin making the user reuse the same secondary dns.

**Comment by virgil** [comment]
for now close the ticket.  I've found other ways to achieve what I needed.
 just get the iframe thing.  that's what really matters.

-V
