### ISSUE TITLE
Alias /gettor and /checktor under /globaleaks/gettor and /globaleaks/checktor

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#222]
This ticket is to alias /gettor and /checktor under /globaleaks/gettor and /globaleaks/checktor URLs.

The resources /gettor and /checktor will be also available under the path describe above.

This is to facilitate the deployment behind a reverse-proxy following the implementation of https://github.com/globaleaks/GlobaLeaks/issues/1130 to strongly simplify https://github.com/globaleaks/GlobaLeaks/wiki/Integration-Guide and https://github.com/globaleaks/GlobaLeaks/issues/1128

**Comment by evilaliv3** [comment]
as all the tickets dicussed here are now implemented in globaleaks not requiring any change on the tor2web side, this ticket can be closed.

**Comment by chojar** [comment]
Witam, dziekuje za podpowiedz probowałem rozwiazac ten problem ale nic nie
wskurałem wyswietla sie tylko interia polski portal i finito . dam sobie
luz z ta kwestia .pozdrawiam

2015-05-18 22:50 GMT+02:00 Giovanni Pellerano <notifications@github.com>:

**Comment by evilaliv3** [comment]
i see, i see
