### ISSUE TITLE
Improve GetTor wiki

### ISSUE THREAD

**Issue by ilv** [globaleaks/Tor2web#224]
Since I don't have write permissions on the wiki, I've cloned it and upload my changes [here](https://github.com/ilv/Tor2web-3.0-wiki/blob/master/GetTor.md). I know I did various changes, but I think is clearer now. I'm opening this as a new ticket in case it needs further discussion. cc @evilaliv3 @fpietrosanti #168

**Comment by evilaliv3** [comment]
Good for me! well done @ilv, thanks!

**Comment by ilv** [comment]
Great, I see this has been updated on the wiki, so I'm closing it. Thanks!

**Comment by evilaliv3** [comment]
thanks to you bro'
