### ISSUE TITLE
URL regex blocklist

### ISSUE THREAD

**Issue by virgil** [globaleaks/Tor2web#230]
I've noticed that a most of the URLs on my blocklist of Bad Stuff (tm) use the same URL directory structure.  I would like an easy way to specify a regex to block.

**Comment by fpietrosanti** [comment]
Related To #151 discussion

**Comment by fpietrosanti** [comment]
@virgil Would you please report back implementation status on #151 and document on Wiki the Regexp based blocking functionality? Tnx
