### ISSUE TITLE
Tor2web failure in starting up due to apparmor does not give useful error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#249]
Tor2web failure in starting up due to apparmor does not give useful error.

When Tor2web start on a system that does not have Apparmor enabled, it die silently without any informative/debugging error that would enable the system administrator to understand "what's going on":

root@XXXXXXX:~# /etc/init.d/tor2web start
   ...fail!

In that case the workaround was to disable /etc/default/tor2web and set APPARMOR_SANDBOXING=0 .

This ticket is to:
- detect apparmor non working condition
- notify to the user at startup time with a useful error
- provide guidance on how to enable apparmor on the kernel or disable from tor2web

**Comment by evilaliv3** [comment]
@fpietrosanti as in GlobaLeaks init script Tor2web does:

        if [ "${APPARMOR_STARTED}" -eq "0" ]; then
          log_end_msg 0 "Unable to initialized AppArmor! AppArmor is probably disabled, please enable it by following instructions at https://wiki.debian.org/AppArmor/HowToUse"
          exit 1
        fi

the issue is that debian and ubuntu by default seems to not output it on the terminal and i'm not finding how to make them do that.

**Comment by fpietrosanti** [comment]
@evilaliv3 We can just workaround it as:
if [ "${APPARMOR_STARTED}" -eq "0" ]; then
      echo "Unable to initialized AppArmor! AppArmor is probably disabled, please enable it by following instructions at https://wiki.debian.org/AppArmor/HowToUse"
      exit 1
    fi

by adding to log_end_msg() another line with echo() .

That way will always works with only minor drawbacks that will possibly, on some system, output that line twice.

**Comment by evilaliv3** [comment]
if we should decide to not be standard, i suggest to avoid using log_end_msg() in general and always use echo. a lot of init script already included in debian do that.

but i discourage using both

**Comment by evilaliv3** [comment]
Ok for this use case (simply for apparmor on tor2web, and both for apparmor/iptables failures on GlobaLeaks) ive duplicated the error message also using "echo" making it more verbose and informative.

the final one is:

            echo "Unable to initialize AppArmor!"
            echo "AppArmor is probably disabled; please enable it by following instructions at https://wiki.debian.org/AppArmor/HowToUse"
            echo "If you understand the risks involved and you know what you are doing, you can disable Tor2web's Apparmor support by editing /etc/default/tor2web and configuring APPARMOR_SANDBOXING=0"
            exit 1
