### ISSUE TITLE
Issue setting SSL cert

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/Tor2web#253]
Firefox says cert chain is incomplete.

I already tried thousands of combinations in the cert.pem file. I'm trying to install a Globalsign AlphaSSL sha256 G2 wildcard certificate.

Any clue on how the cert.pem file should look like?

**Comment by evilaliv3** [comment]
@infosquatter: you should test your domain with https://www.ssllabs.com/ssltest/analyze.html

in the cert.pem file you should put only one certificate and inside the intermediate file you should put ordered all the chain certificates.

default paths if you have not changed them are:
# ssl_cert = /home/tor2web/certs/tor2web-cert.pem
# ssl_intermediate = /home/tor2web/certs/tor2web-intermediate.pem

**Comment by evilaliv3** [comment]
closing ths as outdated.

let me know @infosquatter if you still have issues of this kind.
