### ISSUE TITLE
Automatically generate DH parameters on startup, if those are not already generated

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#260]
When Tor2web is installed it do require to have a DH parameter file that must be manually generated.

This ticket is to automatically generate DH parameters on startup, if those where not already generated

**Comment by evilaliv3** [comment]
good idea! :)

this will make the process more smoth in automatizing the process making it even more secure as built-in.

**Comment by evilaliv3** [comment]
I tried to implement this feature but it seems that functions for writing PEM file are not usable from python.

the implemented code is:
```python
import os
from OpenSSL._util import (ffi as _ffi,
                                   lib as _lib)

dhfile = "./a.pem"
if not os.path.isfile(dhfile):
    dh = _lib.DH_new()
    _lib.DH_generate_parameters_ex(dh, 2048, 2L, _ffi.NULL)
    _lib.PEM_write_DHparams(dhfile, dh)
```

the error that i get running this is: 
```AttributeError: 'module' object has no attribute 'PEM_write_DHparams'```

the same happen if i try to use PEM_write_bio_DHparams

**Comment by fpietrosanti** [comment]
That command, can be executed at first starts directly from init script, if the tor2web-dh.pem file does not exists:
cd /home/tor2web/certs/ && openssl dhparam -out tor2web-dh.pem 2048

**Comment by evilaliv3** [comment]
my patch for pyca/cryptography has been merged, starting from pyopenssl 0.15.1 it will be possible to do this directly from python inside tor2web.

for now i agree that we can do this from the init script but that is not immediate as we are an other time victim of your suggestions @fpietrosanti! :P
infact currently tor2web allow the user to change the paths of certificates and diffiehelman files, and this path are written in /etc/tor2web.conf and parsed at python time by tor2web, so there is no chance we can have them in the init script!

waiting for yours! besos!

**Comment by evilaliv3** [comment]
ok i'm able to write from python a PKCS#3 file with the DH parameters, now i should understand how to reload it that's not so immediate and there is no documentation at all

**Comment by fpietrosanti** [comment]
baam https://github.com/globaleaks/Tor2web/commit/7934693411fdc206f1ba54e189b22308b12ca2f8

**Comment by evilaliv3** [comment]
i've also updated the installation guide removing any reference to the diffie helman parameters generation

dh is no a techie only secret, that that will happen automagically for the tor2web users and expert techies will find it's own way to generate fancy hand crafted dh parameters!
