### ISSUE TITLE
Make Tor2web be able to use the dummy proxy mode together with the host map configuration

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/Tor2web#276]
It would be valuable for the GlobaLeaks setups and on other general use cases to have the possibility to configure in the the host map file also HTTPS servers in order to be able to map a Tor2web domain onto an external service running a simple web server (e.g. GlobaLeaks).

This would simplify deployments where a single Tor2web server is used as forwarder for multiple GlobaLeaks setups.

\cc @fpietrosanti

**Comment by fpietrosanti** [comment]
Duplicated of #167

**Comment by evilaliv3** [comment]
(love)
