### ISSUE TITLE
wiki / install guide - patching no longer needed

### ISSUE THREAD

**Issue by awk0324** [globaleaks/Tor2web#288]
the patch for https://trac.torproject.org/projects/tor/ticket/6031 is
no longer needed and patching actually fails on >=0.2.6.7
the corresponding section can be removed from Installation-Guide.md

**Comment by evilaliv3** [comment]
@awk0324 can you clarify why you think the patch is no longer needed? the patch is not working anymore ok but if aligned to latest Tor codebase it would still be valid in my opinion.

**Comment by evilaliv3** [comment]
Patch rebased on current Tor codebase and wiki updated!

Thanks @awk0324
