### ISSUE TITLE
tor2web 3.1.51 doesn't create /etc/tor2web.conf.example

### ISSUE THREAD

**Issue by filternetz** [globaleaks/Tor2web#291]
Hi, I recently installed tor2web 3.1.51 and wanted to edit /etc/tor2web.conf.example for production. However, it couldn't be found.

As an user, I expected /etc/tor2web.conf.example to exist, however, it isn't there.
```
root@secure:/home/tor2web/certs# dpkg --list | grep tor2web
ii  tor2web                          3.1.51                           all          Tor2web proxy.

root@secure:/home/tor2web/certs# /etc/init.d/tor2web start
 * Enabling Tor2web Apparmor Sandboxing...
 * Starting Tor2web tor2web...
 * Starting tor daemon...
   ...done.
Tor2web Startup Failure: cannot open config file (/etc/tor2web.conf)
Tor2web Startup Failure: cannot open config file (/etc/tor2web.conf)
   ...fail!
```

**Comment by evilaliv3** [comment]
@filternetz recently we identified more valuable to put the default configurations in /usr/share/tor2web/confs to not mess up /etc.

```
root@tor2web:~# ls /usr/share/tor2web/data/conf/tor2web-* -al
-rw-r--r-- 1 root root 3529 Feb 25 17:54 /usr/share/tor2web/data/conf/tor2web-default.conf
-rw-r--r-- 1 root root 1864 Feb 25 17:54 /usr/share/tor2web/data/conf/tor2web-globaleaks.conf
```

do you have any suggestion about that?

**Comment by filternetz** [comment]
Right, I didn't look there. I think my only suggestion is to update the documentation :)

**Comment by evilaliv3** [comment]
Done! thank you sir! https://github.com/globaleaks/Tor2web/wiki/Installation-Guide

**Comment by filternetz** [comment]
:+1:
