### ISSUE TITLE
URL Blank

### ISSUE THREAD

**Issue by akramtariqkhan** [globaleaks/Tor2web#297]
URL : 45.32.27.107 

How to access a onion site on it ?
Used translation in config. Please help

**Comment by akramtariqkhan** [comment]
Every page works except, https://uj3wazyk5u4hnvtk.kickasspiratebay.com/ any idea why ?

**Comment by chojar** [comment]
blad serwera

**Comment by virgil** [comment]
move to close issue.

**Comment by evilaliv3** [comment]
what do you meand @virgil ?

**Comment by virgil** [comment]
I mean there's no valid URLs here to fix.  Ergo shold close issue.
