### ISSUE TITLE
Adding "\"(backslash) after scheme does not rewrite  

### ISSUE THREAD

**Issue by intchloe** [globaleaks/Tor2web#299]
Hello,

adding "\" after the scheme does not rewrite the domain. Chrome will still see this as valid. Example:

https://i.imgur.com/evA9XZt.png

**Comment by evilaliv3** [comment]
@intchloe: what is the use case?

as far that i know a "\" is not a valid character for an hidden service name.
if yes could you provide me the reference you are reading?

**Comment by virgil** [comment]
I looked into this issue.  I recognize there exists a URL that's not be rewritten, but it's unclear to me that it should be rewritten.  It's a URL that's designed to cause funny security problems.  Unclear we should be bending over backward to make intentionally funny URLs work.  If there was a case of people making this mistake in the wild would be more inclined to fix.

**Comment by evilaliv3** [comment]
i agree. if no valid reasons are proivded let's consider this ticket closed.
