### ISSUE TITLE
Make subdomains work with HTTPS

### ISSUE THREAD

**Issue by virgil** [globaleaks/Tor2web#300]
Example problem URL: https://daily.muflax65ngodyewp.onion.to/

Unfortunately, wildcard certificates only go one-level down, i.e., \*.onion.to, but not to \*.\*.onion.to .

I see two solutions:

1. Every time we detect a subdomain, automatically apply for a Lets Encrypt Certificate to that subdomain.
2. We do some subdomain rewriting.  Particularly, 

    `daily_muflax65ngodyewp.onion.to <-> daily.muflax65ngodyewp.onion.to`

Comments appreciated @evilaliv3 @0x0ddba11 .

**Comment by virgil** [comment]
Right now I'm leaning towards just leaving this as a wontfix.

**Comment by virgil** [comment]
And now I'm leaning towards the underscore rewrite.  Presumably underscores are less common than .onion subdomains.  So it's a net win.

**Comment by virgil** [comment]
At onion.link we are pushing forward with rewriting '.' -> '_' to make subdomains for HTTPS work.  It's going to break sites that use a literal '_', and that's just a sacrifice we are willing to make.  If official tor2web wants to do the same we'll share the patch.

**Comment by NSkelsey** [comment]
@virgil if you open a pull (or share the code) I can bug @evilaliv3 enough to accept the merge.
