### ISSUE TITLE
Update Tor patch for 0.2.9.x series

### ISSUE THREAD

**Issue by filternetz** [globaleaks/Tor2web#314]
When compiling Tor (0.2.9.8) and trying to apply the patch that is listed. I get the following output:

<pre>
~/tor2web-buildenv/debian-packages/tor-0.2.9.8# patch -p1 < patch_hs.patch
patching file src/common/compat.h
Hunk #1 succeeded at 638 with fuzz 1 (offset 96 lines).
patching file src/or/or.h
Hunk #1 succeeded at 624 (offset 1 line).
patching file src/or/reasons.c
Hunk #1 succeeded at 78 (offset 6 lines).
Hunk #2 succeeded at 143 (offset 11 lines).
patching file src/or/rendclient.c
Hunk #1 succeeded at 1224 (offset 12 lines).
Hunk #2 FAILED at 1232.
1 out of 2 hunks FAILED -- saving rejects to file src/or/rendclient.c.rej
patching file src/tools/tor-resolve.c
Hunk #1 succeeded at 178 (offset 11 lines)
</pre>

**Comment by NSkelsey** [comment]
@filternetz thanks for reporting. 

Can you please provide the system you are patching for? Clearly these patches need to get updated.

The default package with the normal distribution of `Tor` coming from apt.globaleaks.org works for me on ubuntu 14.04 installations. I believe as a quick work around you can use that instead of trying to apply these Tor patches.

**Comment by filternetz** [comment]
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-24-generic x86_64) :)

**Comment by NSkelsey** [comment]
After looking at the patches, my understanding is that they only add more descriptive information for the tor2web server to consume. You will be safe without them.

**Comment by filternetz** [comment]
Cool! It runs fine without, but I didn't really took a hard look to be honest.

**Comment by NSkelsey** [comment]
The tor project has moved trusty to `v2.9.x` [series](http://deb.torproject.org/torproject.org/dists/trusty/main/binary-amd64/Packages). We need to update `src/or/rendclient.c` to fix the normal installation path.

**Comment by fpietrosanti** [comment]
The Tor2web tor's patch is probably totally un-needed given the new support available in Tor to improve performance of Tor Onion Services (client-side connecting directly to RendezVous and server-side to be one-hop onion server).

We shall update the documentation to just remove the patch and open-up a ticket for performance improvement experimentation and documentation of Tor's configurations up to volounteers.

**Comment by evilaliv3** [comment]
@fpietrosanti your comment is out of context!

**Comment by evilaliv3** [comment]
The patch is the patch for making error descriptive! 

i agree anyhow to remove this as we do not use it that much in tor2web.
in addition the setup of this patch is an additional step for the delployment of GlobaLeaks setups.

regargin your Tor Onion Services also i've a big doubt that they will replace completely the Tor2web mode.
One thing is the client optimization from the Tor2web side, one thing is the serverside optimization from the GlobaLeaks node. both may be interesting and non of them replace the other.

**Comment by evilaliv3** [comment]
The patch is dead, long death to the patch!

**Comment by filternetz** [comment]
Thanks! Happy that I don't have to compile it in anymore :)
