### ISSUE TITLE
Tor compile fail

### ISSUE THREAD

**Issue by filternetz** [globaleaks/Tor2web#333]
When attempting to compile Tor 0.3.0.9 on Jessie with debuild -rfakeroot -uc -us I get:

1/896 TESTS FAILED. (2 skipped)
Makefile:9715: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/jurre/tor2web-buildenv/debian-packages/tor-0.3.0.9/build'
dh_auto_test: make -j1 test returned exit code 2
debian/rules:25: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by evilaliv3** [comment]
Thanks @filternetz, i've still not retested the failure but i will do asap.

**Comment by evilaliv3** [comment]
Closing as duplicated for https://github.com/globaleaks/Tor2web/issues/327
