### ISSUE TITLE
Create new branch to receive testsuite pull requests.

### ISSUE THREAD

**Issue by cheako** [globaleaks/Tor2web#336]
I'm unable to create pull request(s) to a branch that does not exist.

git push origin master:testsuite; # Should suffice.

**Comment by evilaliv3** [comment]
@cheako: there is no need for our repository to already host a repository with the name of your patch. it all the necessary for making pull request is the following:
- you have simply to clone the repository on your user
- you have to create the branch for your patches on your repoitory
- when your are ready to perform a pull request you can simply make it from your repository via the github interface.

Via github directly then you will be able to issue the pull request.

Try to make this and eventually feel free to reach out to us again.

**Comment by cheako** [comment]
Actually currently I can only create pull request against the master branch and that's not what I want to do.

**Comment by cheako** [comment]
I'm back from camping.  It's time for someone else to take ownership of this test suite.  I may add some tests in a few weeks but it's unlikely I will ever learn enough about Tor2web to complete this implementation.

**Comment by evilaliv3** [comment]
Thanks Micheal all your valuable suggestions are welcome, if you could just
open the branch on your repository and commit what you did I will take care
of move it forward integrating it.

Grazie!
