### ISSUE TITLE
error: pyasn1 0.1.9 is installed but pyasn1==0.3.2 is required by set(['pyasn1-modules'])

### ISSUE THREAD

**Issue by cheako** [globaleaks/Tor2web#338]
Looks like the wrong version of pyasn1 is required.
https://travis-ci.org/cheako/Tor2web-1/builds/265028937#L1586

**Comment by evilaliv3** [comment]
Thanks @cheako this actually requires this exact patch that we just applied few times ago to globaleaks: https://github.com/globaleaks/GlobaLeaks/commit/3797052aee59d0fd1653bc4059455def72bf1879

**Comment by evilaliv3** [comment]
Patch applied in commit https://github.com/globaleaks/Tor2web/commit/a701b5f004ff8c011468af19a2a55ca58ed7ddf0 and released in version 3.1.70

**Comment by cheako** [comment]
[This is](https://github.com/cheako/Tor2web-1/commit/e0053f8bdaa082a7a989931aef1de645c4fbfa0f) a patch that fixes this issue.

**Comment by cheako** [comment]
This issue has NOT been corrected.
