### ISSUE TITLE
Does tor2web support v3 onions?

### ISSUE THREAD

**Issue by hybla0** [globaleaks/Tor2web#366]
Hi,
I am trying to access a v3 onion I just created via tor2web, but I am getting error messages such as "invalid hostname" and "the entered url is invalid", but the onion service loads into my web browser

**Comment by evilaliv3** [comment]
Yes @hybla0 

Tor2web 3.2.0 supports onion services v3

Which version of Tor2web are you using?

**Comment by evilaliv3** [comment]
Closing as the user making the questin disappeared!
